language: ruby
before_install:
  - gem install bundler -v "< 2.0"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - cp config/settings.yml{.travis,}
  - cp config/database.yml{.example,}
  - bundle exec rake db:setup
  - bundle exec rackup faye.ru -s thin -E production -D
rvm:
  - 2.1.1
branches:
  only:
    - master
cache: bundler
notifications:
  webhooks:
    urls:
    - https://buildlight.collectiveidea.com/
    on_start: always
