name: CI

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: correcthorsebatterystaple
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgres://test:correcthorsebatterystaple@localhost:5432/test
      RAILS_ENV: test
      RUBYOPT: --enable=frozen-string-literal

    steps:
    - uses: actions/checkout@master

    # setup-ruby can infer the Ruby version
    - name: Create .ruby-version based on Gemfile
      run: grep -oP '^ruby .\K\d+\.\d+\.\d+' Gemfile > .ruby-version

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - uses: actions/cache@v4
      with:
        path: ~/.yarn-cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Yarn Install
      run: yarn install --cache-folder ~/.yarn-cache

    - name: App Setup
      run: bin/setup

    - name: Start Faye
      run: bundle exec rackup faye.ru -s thin -E production -D

    - name: Zeitwerk Check
      run: bundle exec rake zeitwerk:check

    - name: Build CSS
      run: yarn build:css

    - name: Standard
      run: bundle exec standardrb

    - name: Run Tests
      run: bundle exec rspec --format progress --color
